### ISSUE TITLE
About phaselink_dataset parameters 

### ISSUE THREAD

**Issue by ecastillot** [interseismic/PhaseLink#2]
Good morning,

I tried to run phaselink_dataset.py but some errors appear at this moment. 

`Traceback (most recent call last):
  File "phaselink_dataset.py", line 325, in <module>
    pTT = tt_interp(params['tt_table']['P'], params['datum'])
KeyError: 'tt_table'`

In json file, I noted that tt_table and datum keys doesn't exist. I suposse that tt_table is the path of the travel time table but I don't know what is datum, can you explain me please? in this way I I can put it in json file and try again.

Thanks a lot

**Comment by interseismic** [comment]
Sorry, didn't see this comment. I've just added a manual for this code, which should be helpful for you. But in any case, the datum is the reference depth for the velocity model. This probably would be 0 but if you use something else, then it needs to match that value.
